In [10]:
import numpy as n

In [11]:
np.random.seed(0)

In [12]:
m = 4
n = 3

In [13]:
A = np.random.randn(m,n)

In [14]:
A

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351]])

In [15]:
a_1 = A[:,0]

In [16]:
a_1

array([1.76405235, 2.2408932 , 0.95008842, 0.4105985 ])

In [18]:
a_1 = A[:,0] .reshape(-1,1)
a_2 = A[:,1] .reshape(-1,1)
a_3 = A[:,2] .reshape(-1,1)

In [19]:
a_1

array([[1.76405235],
       [2.2408932 ],
       [0.95008842],
       [0.4105985 ]])

In [20]:
a_2

array([[ 0.40015721],
       [ 1.86755799],
       [-0.15135721],
       [ 0.14404357]])

In [21]:
a_3

array([[ 0.97873798],
       [-0.97727788],
       [-0.10321885],
       [ 1.45427351]])

In [22]:
AT = np.vstack([a_1.T, a_2.T, a_3.T])

In [23]:
AT

array([[ 1.76405235,  2.2408932 ,  0.95008842,  0.4105985 ],
       [ 0.40015721,  1.86755799, -0.15135721,  0.14404357],
       [ 0.97873798, -0.97727788, -0.10321885,  1.45427351]])

In [24]:
A.T

array([[ 1.76405235,  2.2408932 ,  0.95008842,  0.4105985 ],
       [ 0.40015721,  1.86755799, -0.15135721,  0.14404357],
       [ 0.97873798, -0.97727788, -0.10321885,  1.45427351]])

In [25]:
np.prod(AT == A.T)

1

In [28]:
A = np.array([[1,2],[3,4],[5,6]])

In [29]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
B = np.array([[1,2],[1,1],[1,1]])

In [31]:
B

array([[1, 2],
       [1, 1],
       [1, 1]])

In [32]:
np.matmul(B.T, A)

array([[ 9, 12],
       [10, 14]])

In [33]:
A = np.array([[1,1,1],[2,3,4]])

In [34]:
A

array([[1, 1, 1],
       [2, 3, 4]])

In [35]:
A.shape

(2, 3)

In [36]:
B = np.random.randn(4,3)

In [37]:
C = np.random.randn(3,8)

In [38]:
B

array([[ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502]])

In [39]:
C

array([[ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
         1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897,  1.23029068,
         1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036]])

In [40]:
np.matmul(B,C).shape

(4, 8)

In [41]:
A = np.random.randn(4,6)

In [42]:
A

array([[-1.61389785, -0.21274028, -0.89546656,  0.3869025 , -0.51080514,
        -1.18063218],
       [-0.02818223,  0.42833187,  0.06651722,  0.3024719 , -0.63432209,
        -0.36274117],
       [-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
        -0.40178094],
       [-1.63019835,  0.46278226, -0.90729836,  0.0519454 ,  0.72909056,
         0.12898291]])

In [43]:
A[1,2]

0.06651722238316789

In [44]:
A[3,:]

array([-1.63019835,  0.46278226, -0.90729836,  0.0519454 ,  0.72909056,
        0.12898291])

In [46]:
A[:,0]

array([-1.61389785, -0.02818223, -0.67246045, -1.63019835])

In [47]:
A[:,0].reshape(-1,1)

array([[-1.61389785],
       [-0.02818223],
       [-0.67246045],
       [-1.63019835]])