In [4]:
import numpy as np

In [5]:
np.random.seed(0)

In [6]:
m = 4
n = 5

In [7]:
B = np.random.randn(4,5)

In [8]:
B

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [9]:
y = np.random.randn(n,1)

In [10]:
y

array([[-2.55298982],
       [ 0.6536186 ],
       [ 0.8644362 ],
       [-0.74216502],
       [ 2.26975462]])

In [11]:
By = np.matmul(B,y)
print('By=',By)

By= [[-0.8202151 ]
 [ 3.99370055]
 [ 2.15782468]
 [-2.22359117]]


In [12]:
By_right = 0
for i in np.arange(n):
    By_right += B[:,i].reshape(-1,1)*y[i]

In [13]:
By_right

array([[-0.8202151 ],
       [ 3.99370055],
       [ 2.15782468],
       [-2.22359117]])

In [14]:
By == By_right

array([[False],
       [False],
       [ True],
       [ True]])

In [15]:
n = 5

In [16]:
s_1 = np.random.randn(5,1)
s_2 = np.random.randn(5,1)
s_3 = np.random.randn(5,1)
s_4 = np.random.randn(5,1)

In [17]:
s_1

array([[-1.45436567],
       [ 0.04575852],
       [-0.18718385],
       [ 1.53277921],
       [ 1.46935877]])

In [18]:
x_1 = np.vstack([ 1 , s_1])

In [19]:
S = np.vstack([s_1.T , s_2.T, s_3.T, s_4.T])

In [20]:
S

array([[-1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218]])

In [21]:
one_vec = np.ones((4,1))

In [22]:
X = np.hstack([one_vec,S])

In [24]:
theta = np.random.randn(n+1,1)

In [25]:
theta.shape

(6, 1)

In [26]:
Xtheta = np.matmul(X ,theta)

In [27]:
Xtheta

array([[ 0.07977516],
       [ 1.82756039],
       [-1.26482466],
       [ 2.56661151]])