In [1]:
import numpy as np

다음 행렬을 고려해서 답을 하세요: $A\in\mathbb{R}^{2\times 3}$

\begin{align}
A &= \begin{bmatrix}
10 & 20 & 30\\
40 & 50 & 60
\end{bmatrix}\\
&= \begin{bmatrix}
a^{(1)} & a^{(2)} & a^{(3)}
\end{bmatrix}\\
\end{align}


### Problem 1
다음 행렬을 2D array로 `A`라는 변수로 저장하세요.
- 유용할 수 있는 함수: `np.array`

In [7]:
## 답작성
A = np.array([[10,20,30],[40,50,60]])

In [8]:
print('A=', A)

A= [[10 20 30]
 [40 50 60]]


### Problem 2
$A$ 행렬의 2번째 row vector를 $A_{2:}$를 `a2_row`라는 변수에 저장하세요

In [10]:
## 답작성
a2_row = A[1]

In [11]:
a2_row

array([40, 50, 60])

In [12]:
a2_row.ndim

1

In [13]:
b = np.array([1,2,3])

In [14]:
b

array([1, 2, 3])

In [16]:
b2d = np.array([[1,2,3]])

In [18]:
b2d.shape

(1, 3)

In [19]:
bcol = np.array([[1],[2],[3]])

In [20]:
bcol

array([[1],
       [2],
       [3]])

In [21]:
bcol.shape

(3, 1)

### Problem 3
`A` 행렬의 2번째 column vector $a^{(2)}$를 `a2`라는 변수에 column vector로 저장하세요
- 유용할 수 있는 함수 `np.reshape`

In [22]:
## 답작성
A

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
a2=A[:,1]

In [24]:
a2

array([20, 50])

In [25]:
a2 = a2.reshape(2,1)

In [26]:
a2

array([[20],
       [50]])

### Problem 4
난수 (정규분포) 발생으로 $B\in\mathbb{R}^{3\times 2}$ 행렬을 생성하고 `B`라는 변수에 저장하세요
- 유용할 수 있는 함수: `np.random.randn()`

In [57]:
## 답작성
B = np.random.randn(3,2)

In [59]:
B

array([[ 0.43681098, -0.57773697],
       [ 2.38036322, -1.518343  ],
       [-0.29240602, -0.77207049]])

### Problem 5
난수 (정규분포) 발생으로 $x^{(i)}\in\mathbb{R}^{2}$, $i=1,2,3$ 벡터을 생성하고 각각 `x1`, `x2`, `x3`라는 변수에 저장하세요

In [60]:
## 답작성

x1 = np.random.randn(2,1)
x2 = np.random.randn(2,1)
x3 = np.random.randn(2,1)

In [61]:
x3.shape

(2, 1)

### Problem 6
$x^{(i)}$들을 column vector로 하는 행렬 $X_\text{col}$를 생성하고 `X_col`라는 변수에 저장하세요. 즉,

\begin{align*}
X_\text{col} = \begin{bmatrix}
x^{(1)} & x^{(2)} & x^{(3)} 
\end{bmatrix}
\end{align*}

- 유용할 수 있는 함수 `np.hstack`.

In [62]:
## 답작성
X_col = np.hstack([x1,x2,x3])

In [63]:
X_col

array([[-0.6725207 ,  2.329532  ,  1.1541109 ],
       [ 1.96075943,  0.30370716,  0.68643099]])

In [64]:
x3

array([[1.1541109 ],
       [0.68643099]])

##### Vector Transpose
벡터 $x\in\mathbb{R}^n$이 있다고 가정했을때, $x$의 transpose는 $x^\top$ 또는 $x^{T}$로 표기하며, row vector는 column vector로, 또는 그 반대로 변환하는 연산자다

- 유용할 수 있는 함수 `np.transpose`
- 또는, `x.T`

### Problem 7
$x^{(1)}$의 전치를 구하세요

In [65]:
## 답작성
x1

array([[-0.6725207 ],
       [ 1.96075943]])

In [66]:
x1.T

array([[-0.6725207 ,  1.96075943]])

### Problem 8 
$(x^{(i)})^T$를 row vector로 하는 행렬 $X\in\mathbb{R}^{3\times 2}$를 구하고, `X`라는 변수에 저장하세요. 즉,
\begin{align*}
X = \begin{bmatrix}
(x^{(1)})^T \\
(x^{(2)})^T \\
(x^{(3)})^T \\
\end{bmatrix}
\end{align*}
를 구하세요. 

- 유용할 수 있는 함수 `np.vstack`.

In [67]:
## 답작성
X = np.vstack([x1.T , x2.T , x3.T])

In [68]:
x1

array([[-0.6725207 ],
       [ 1.96075943]])

In [69]:
X

array([[-0.6725207 ,  1.96075943],
       [ 2.329532  ,  0.30370716],
       [ 1.1541109 ,  0.68643099]])

### Problem 9

$X_\text{col}^T = X$임을 보이세요


In [70]:
## 답작성
X_col.T

array([[-0.6725207 ,  1.96075943],
       [ 2.329532  ,  0.30370716],
       [ 1.1541109 ,  0.68643099]])

In [71]:
X

array([[-0.6725207 ,  1.96075943],
       [ 2.329532  ,  0.30370716],
       [ 1.1541109 ,  0.68643099]])

In [72]:
X_col.T==X

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [74]:
X.reshape(6,1)

array([[-0.6725207 ],
       [ 1.96075943],
       [ 2.329532  ],
       [ 0.30370716],
       [ 1.1541109 ],
       [ 0.68643099]])